---
  NeutronBGPVPN.create_bgpvpn_assoc_disassoc_routers:
    -
      args: {}
      runner:
        type: "constant"
        times: 10
        concurrency: 2
      context:
        users:
          tenants: 1
          users_per_tenant: 1
        quotas:
          neutron:
            router: -1
      sla:
        failure_rate:
          max: 0